version: "3.9"

services:
  create-service:
    build: ./p-go-create
    container_name: microservicio-create
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    networks:
      - parcial_go_mongo_net

  delete-service:
    build: ./p-go-delete
    container_name: microservicio-delete
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - parcial_go_mongo_net

  read-service:
    build: ./p-go-read
    container_name: microservicio-read
    env_file:
      - .env
    restart: always
    ports:
      - "5000:5000"
    networks:
      - parcial_go_mongo_net

  tester:
    image: curlimages/curl
    depends_on:
      - create-service
      - delete-service
      - read-service
    networks:
      - parcial_go_mongo_net
    entrypoint: >
      sh -c "
        sleep 15 &&
        curl -s --fail http://create-service:8080 &&
        curl -s --fail http://delete-service:3000 &&
        curl -s --fail http://read-service:5000
        || exit 1
      "
    profiles:
      - test

networks:
  parcial_go_mongo_net:
    external: true
