version: "3.9"

services:
  # ===========================
  # Microservicios GO
  # ===========================
  create-service:
    build: ./p-go-create
    container_name: microservicio-create
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    networks:
      - parcial_go_mongo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      retries: 5
      timeout: 2s

  delete-service:
    build: ./p-go-delete
    container_name: microservicio-delete
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - parcial_go_mongo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      retries: 5
      timeout: 2s

  read-service:
    build: ./p-go-read
    container_name: microservicio-read
    env_file:
      - .env
    restart: always
    ports:
      - "5000:5000"
    networks:
      - parcial_go_mongo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      retries: 5
      timeout: 2s

  update-service:
    build: ./p-go-update
    container_name: microservicio-update
    env_file:
      - .env
    restart: always
    ports:
      - "5001:5001"
    networks:
      - parcial_go_mongo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 5s
      retries: 5
      timeout: 2s

  # ============================
  # Servicio para test de endpoints
  # ============================
  tester:
    image: curlimages/curl
    depends_on:
      create-service:
        condition: service_healthy
      delete-service:
        condition: service_healthy
      read-service:
        condition: service_healthy
      update-service:
        condition: service_healthy
    networks:
      - parcial_go_mongo_net
    entrypoint: >
      sh -c "
        curl -s --fail http://create-service:8080 &&
        curl -s --fail http://delete-service:3000 &&
        curl -s --fail http://read-service:5000 &&
        curl -s --fail http://update-service:5001
        || exit 1
      "
    profiles:
      - test

# ===========================
# Red compartida
# ===========================
networks:
  parcial_go_mongo_net:
    external: true
