name: CI p-go-delete

on:
  push:
    branches: ["main"]
    paths:
      - "../.."
      - ".github/workflows/delete.yml"

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: p-go-delete

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go mod tidy
        run: go mod tidy

      - name: Run Tests
        run: go test ./...

      - name: Build binary
        run: go build -o app

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/p-go-delete:latest \
            .

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository_owner }}/p-go-delete:latest
